name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Markdown Lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: /github/workspace
