name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install remark-cli and remark-preset-lint-consistent
        run: npm install -g remark-cli remark-preset-lint-consistent

      - name: Run markdown lint
        run: npx remark . --use remark-preset-lint-consistent --frail
